# Generated by Django 5.1 on 2024-08-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BR', 'Brasil'), ('JP', 'Japan'), ('KR', 'Coreia do Sul'), ('CN', 'China'), ('IN', 'India'), ('UK', 'Inglaterra'), ('FR', 'França'), ('IT', 'Italia'), ('DE', 'Alemanha'), ('CA', 'Canada'), ('AU', 'Australia'), ('CO', 'Colombia'), ('CL', 'Chile'), ('BO', 'Bolivia'), ('UY', 'Uruguai')], max_length=100, null=True)),
            ],
        ),
    ]
