# Generated by Django 5.1 on 2024-08-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BR', 'Brasil'), ('JP', 'Japão'), ('KR', 'Coréia do Sul'), ('CN', 'China'), ('IN', 'India'), ('UK', 'Inglaterra'), ('FR', 'França'), ('IT', 'Italia'), ('DE', 'Alemanha'), ('CA', 'Canada'), ('AU', 'Australia'), ('CO', 'Colombia'), ('CL', 'Chile'), ('BO', 'Bolivia'), ('UY', 'Uruguai'), ('AR', 'Argentina'), ('PE', 'Peru'), ('PT', 'Portugal')], max_length=100, null=True),
        ),
    ]
